### ISSUE TITLE
기능 중복

### ISSUE THREAD

**Issue by RanolP** [DevCrafters/MCLibrary#1]
ItemUtils#getItemAmount과 PlayerUtils#hasItemAmount은 기능이 유사한 것으로 추정되며, 
ItemUtils.ItemRemoval#removeItem은 PlayerUtils#takeItem와 기능이 유사한 것으로 추정됨.

+ PlayerUtils#isHasItem은 네이밍이 대체 왜 이렇...

**Comment by EntryPointKR** [comment]
참고
b344846cdf02926329fedc5e369b06e8b95cee7e
e0ba378fb34c405abaf871f1a20f95241bea5a58
