### ISSUE TITLE
성능 이슈

### ISSUE THREAD

**Issue by RanolP** [DevCrafters/MCLibrary#2]
CommandManager#registerCommand 에서 forEach로 람다를 전해주는데, 성능 이슈가 날 가능성이 있는 코드임. 고전적인 foreach로 바꾸는 것을 권장함.

**Comment by EntryPointKR** [comment]
forEach() 와 for-each 두 방식의 속도를 측정한 결과 밀리세컨드로 표현할 수 없을 미세한 정도였습니다.
단순히 forEach() 가 느리다는 이유로 for-each 로 변경해야 된다면 모든 상황에서의 forEach() 사용 자체가 틀린 것이 됩니다.

그렇다면 for-each 가 아닌 forEach() 를 사용해야만 하는 특수한 경우가 있습니까?

**Comment by RanolP** [comment]
이전의 복잡한 로직으로 for-each로 변경한 후 벤치마킹한 결과에서 차이때문에 Stream API나 forEach가 전부 느리다는 고정관념에 사로잡혀있던 듯 합니다. forEach 함수 하나만으로는 그렇게 성능의 차이가 없을 듯 하네요.
