### ISSUE TITLE
네이밍

### ISSUE THREAD

**Issue by RanolP** [DevCrafters/MCLibrary#3]
GUIHelper#isIn 보단 GUIHelper#hasHelper나 GUIHelper#containsHelper로 바꿀 것을 권장함.
GUIHelper.Listener의 이름을 다른 것으로 바꿀 것을 권장함.

**Comment by EntryPointKR** [comment]
helperMap 에 값이 들어가있다는 건 그 엔티티가 GUI 를 보고있다는 의미로 isIn 으로 네이밍하였고
hasHelper 같은 네이밍은 프로그래밍(해쉬맵)에 기준을, isIn 은 기능에 기준을 둔 네이밍이기 떄문에 개인차가 있어 문제라고 보기 힘들겠습니다
